server:
  port: 8881

logging:
  level:
    cn.jay.repository: trace

spring:
  application:
    name: userManger
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.88:3306/autoapi?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Xxx123456
mybatis:
  type-aliases-package: com.test.model
  mapper-locations:
    - mapper/*

